apiVersion: v1
kind: ReplicationController
metadata:
  name: concourse-postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: concourse-postgresql
    spec:
      containers:
      - name: concourse-postgresql
        image: vyshane/postgresql
        env:
        - name: POSTGRES_DB
          value: concourse
        - name: POSTGRES_USER_FILE
          value: /etc/secrets/username
        - name: POSTGRES_PASSWORD_FILE
          value: /etc/secrets/password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data/pgdata
      volumes:
      - name: secrets
        secret:
          secretName: concourse-postgresql-secrets
      - name: postgresql-storage
        emptyDir: {}
